runtime: nodejs
env: flex
service: yote-staging

# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml

automatic_scaling:
  min_num_instances: 1

#[START env_variables]
env_variables:
  GCLOUD_DATASET_ID: yote-919
  NODE_ENV: staging
#[END env_variables]